docs: fix unexported function names in svd doc (#1151)
> QRIteration() is not exported, so I updated the svd.jl documentation
section that suggests such a method exists for the `svd` function. Now
it says to use `alg = LinearAlgebra.QRIteration()` instead of `alg =
QRIteration()` which would produce an error before.

```jl
julia> VERSION
v"1.11.2"

julia> using LinearAlgebra

julia> DivideAndConquer
ERROR: UndefVarError: `DivideAndConquer` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

julia> QRIteration
ERROR: UndefVarError: `QRIteration` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

julia> LinearAlgebra.DivideAndConquer
LinearAlgebra.DivideAndConquer

julia> LinearAlgebra.QRIteration
LinearAlgebra.QRIteration
```

Moved from https://github.com/JuliaLang/julia/pull/56611

---------

Signed-off-by: Chengyu HAN <cyhan.dev@outlook.com>
Co-authored-by: Ali Hamed Moosavian <sahmosavian@gmail.com>