Fix missing `copyto!` methods for triangular matrix types (#54763)
The `_copyto!` methods were not defined for all combinations, and
`copyto!` was also too permissive (it accepted mismatched `uplo`s). This
PR adds the missing methods, and updates the specialized `copyto!` such
that it only accepts combinations with matching `uplo`s. The other cases
will be handled by the fallback method.

Fixes, e.g.:
```julia
julia> using LinearAlgebra

julia> A = [1 2; 3 4];

julia> copyto!(UpperTriangular(A), UnitUpperTriangular(A))
ERROR: MethodError: no method matching _copyto!(::UpperTriangular{Int64, Matrix{Int64}}, ::UnitUpperTriangular{Int64, Matrix{Int64}})
The function `_copyto!` exists, but no method is defined for this combination of argument types.
[...]
```
After this,
```julia
julia> copyto!(UpperTriangular(A), UnitUpperTriangular(A))
2×2 UpperTriangular{Int64, Matrix{Int64}}:
 1  2
 ⋅  1
```